---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: ubuntu
    run_list:
      - recipe[pam_test::default]
    includes:
      - ubuntu-14.04
  - name: centos
    run_list:
      - recipe[pam_test::default]
    includes:
      - centos-7.2
